version: '3.3'

services:
  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1.22.3
    user: root
    ports:
      - "7233:7233"
      - "7234:7234"
      - "7235:7235"
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - ENABLE_ES=false
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - POSTGRES_PASSWORD=temporal
      - DBNAME=temporal
      - POSTGRES_PORT=5432
      - DB=postgresql
      - POSTGRES_HOST=postgresql
      - SERVICES=history,matching,frontend,worker
    depends_on:
      - postgresql
    restart: on-failure
    command: ["bash", "-c", "while ! pg_isready -h postgresql -p 5432 -U temporal; do sleep 1; done; temporal-server start-dev"]

  postgresql:
    container_name: temporal-postgresql
    image: postgres:13
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresql-data: 